### PR TITLE
Update definitions.lua

### PR DESCRIPTION
**Pull request by bhushan**

### CODE REVIEW

**Comment by p00f** [comment]
Also add javascript to the readme and help file

**Comment by bhushan** [comment]
@p00f Updated readme as well

**Comment by p00f** [comment]
Help file too please

**Comment by bhushan** [comment]
helper also updated, did i missed anyother file ?

**Comment by bhushan** [comment]
😅 you were too fast, I updated and pushed, but you already added comment.. Checked all references in project..

**Comment by p00f** [comment]
Thanks!

**Pull request merged**
